<?php

namespace OC\PlatformBundle\Repository;

/**
 * AaaaaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AaaaaRepository extends \Doctrine\ORM\EntityRepository
{
       
}
